doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            user_id: App\User\Infrastructure\Persistence\Doctrine\Type\UserIdType
            email_type: App\User\Infrastructure\Persistence\Doctrine\Type\EmailType
            username: App\User\Infrastructure\Persistence\Doctrine\Type\UsernameType
            hashed_password: App\User\Infrastructure\Persistence\Doctrine\Type\HashedPasswordType
            activation_token: App\User\Infrastructure\Persistence\Doctrine\Type\ActivationTokenType
            puzzle_id: App\Puzzle\Infrastructure\Persistence\Doctrine\Type\PuzzleIdType
            puzzle_session_id: App\Puzzle\Infrastructure\Persistence\Doctrine\Type\PuzzleSessionIdType
            piece_move_id: App\Puzzle\Infrastructure\Persistence\Doctrine\Type\PieceMoveIdType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: false
        mappings:
            User:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/User/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: App\User\Domain\Entity
                alias: User
            Puzzle:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Puzzle/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: App\Puzzle\Domain\Entity
                alias: Puzzle

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool
