; Defaults
zend_extension=xdebug
xdebug.mode=debug
xdebug.client_port=9004
xdebug.client_host=host.docker.internal
xdebug.remote_handler=dbgp
xdebug.start_with_request=yes

; idekey value is specific to Visual Studio Code
xdebug.idekey=PHPSTORM



